version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      USER: root
      PASSWORD: '123'
    depends_on:
      - db

  db:
    container_name: inventorydb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: inventory_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
